### ISSUE TITLE
IS Renderer causing error in console

### ISSUE THREAD

**Issue by simongis** [Esri/WAB-Image-Services-Widgets#13]
I have published a Mosaic Dataset to an Image Service with ArcGIS GIS Server 10.5.  This has a couple of symbology raster templates embedded.  ([Paste of REST endpoint](https://pastebin.com/9Y3i7rCp), and also [RasterFunctionInfos](https://pastebin.com/csj3v9dr)).

These symbology renderers work as expected when  added to ArcGIS Online

![ArcGIS Online](http://i.imgur.com/xQj9L3X.png)

With the one image service added to a Web Map, when I add the IS Renderer widget to Web App Builder Developer Edition (2.4), I get the following error in my console when launching the widget:

```
init.js:113 TypeError: Cannot read property 'length' of undefined
    at Object.rendererRR (Widget.js?wab_dv=2.4:208)
    at Object.<anonymous> (Widget.js?wab_dv=2.4:198)
    at init.js:63
    at c (init.js:103)
    at d (init.js:103)
    at a.Deferred.resolve.callback (init.js:105)
    at c (init.js:104)
    at d (init.js:103)
    at a.Deferred.resolve.callback (init.js:105)
    at c (init.js:104) "TypeError: Cannot read property 'length' of undefined
    at Object.rendererRR (http://simon-pc:3344/webappbuilder/apps/2/widgets/ISRenderer/Widget.js?wab_dv=2.4:208:53)
    at Object.<anonymous> (http://simon-pc:3344/webappbuilder/apps/2/widgets/ISRenderer/Widget.js?wab_dv=2.4:198:23)
    at http://js.arcgis.com/3.20/init.js:63:277
    at c (http://js.arcgis.com/3.20/init.js:103:393)
    at d (http://js.arcgis.com/3.20/init.js:103:182)
    at a.Deferred.resolve.callback (http://js.arcgis.com/3.20/init.js:105:10)
    at c (http://js.arcgis.com/3.20/init.js:104:96)
    at d (http://js.arcgis.com/3.20/init.js:103:182)
    at a.Deferred.resolve.callback (http://js.arcgis.com/3.20/init.js:105:10)
    at c (http://js.arcgis.com/3.20/init.js:104:96)"
```
![ArcGIS Online](http://i.imgur.com/j0hvGNeg.png)

Can someone help me troubleshoot what the issue might be?

**Comment by kushu493** [comment]
Hi Simon,
This is strange. It should work. Can you send me the link to the service so that i can test it out?

Regards,

Kushagra Patel

**Comment by simongis** [comment]
Can you send me an email at sjackson(at)esriaustralia.com.au
I cant find you in the system

**Comment by simongis** [comment]
I published a new result to my image service and it is now behaving as expected.  Not entirely sure what the issue was!  Case closed
